#pragma checksum "C:\Users\vera2\source\repos\NewsWebsite\NewsWebsite\Pages\HomePage.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "a2014ec7b830377abc4d5e602dde886a75280d5c"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(NewsWebsite.Pages.Pages_HomePage), @"mvc.1.0.razor-page", @"/Pages/HomePage.cshtml")]
namespace NewsWebsite.Pages
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.AspNetCore.Mvc.ViewFeatures;
#nullable restore
#line 1 "C:\Users\vera2\source\repos\NewsWebsite\NewsWebsite\Pages\_ViewImports.cshtml"
using NewsWebsite;

#line default
#line hidden
#nullable disable
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"a2014ec7b830377abc4d5e602dde886a75280d5c", @"/Pages/HomePage.cshtml")]
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"90043ec9aee9334ecbb764efdea4c6fd9611f75b", @"/Pages/_ViewImports.cshtml")]
    public class Pages_HomePage : global::Microsoft.AspNetCore.Mvc.RazorPages.Page
    {
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_0 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("src", new global::Microsoft.AspNetCore.Html.HtmlString("~/images/logo.png"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_1 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("class", new global::Microsoft.AspNetCore.Html.HtmlString("nav-link"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_2 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("asp-page", "Login", global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_3 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("asp-page-handler", "Logout", global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        #line hidden
        #pragma warning disable 0649
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext __tagHelperExecutionContext;
        #pragma warning restore 0649
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner __tagHelperRunner = new global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner();
        #pragma warning disable 0169
        private string __tagHelperStringValueBuffer;
        #pragma warning restore 0169
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager __backed__tagHelperScopeManager = null;
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager __tagHelperScopeManager
        {
            get
            {
                if (__backed__tagHelperScopeManager == null)
                {
                    __backed__tagHelperScopeManager = new global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager(StartTagHelperWritingScope, EndTagHelperWritingScope);
                }
                return __backed__tagHelperScopeManager;
            }
        }
        private global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.HeadTagHelper __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_HeadTagHelper;
        private global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.BodyTagHelper __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_BodyTagHelper;
        private global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.UrlResolutionTagHelper __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper;
        private global::Microsoft.AspNetCore.Mvc.TagHelpers.AnchorTagHelper __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper;
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
            WriteLiteral("<html>\r\n");
            __tagHelperExecutionContext = __tagHelperScopeManager.Begin("head", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "a2014ec7b830377abc4d5e602dde886a75280d5c4625", async() => {
                WriteLiteral(@"

    <link rel=""stylesheet"" href=""https://use.fontawesome.com/releases/v5.7.1/css/all.css"" integrity=""sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr"" crossorigin=""anonymous"">

    <link rel=""stylesheet"" type=""text/css"" href=""css/style.css"">
");
            }
            );
            __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_HeadTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.HeadTagHelper>();
            __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_Razor_TagHelpers_HeadTagHelper);
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
            if (!__tagHelperExecutionContext.Output.IsContentModified)
            {
                await __tagHelperExecutionContext.SetOutputContentAsync();
            }
            Write(__tagHelperExecutionContext.Output);
            __tagHelperExecutionContext = __tagHelperScopeManager.End();
            WriteLiteral("\r\n");
            __tagHelperExecutionContext = __tagHelperScopeManager.Begin("body", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "a2014ec7b830377abc4d5e602dde886a75280d5c5874", async() => {
                WriteLiteral("\r\n    <header>\r\n        <div class=\"website-header\">\r\n            ");
                __tagHelperExecutionContext = __tagHelperScopeManager.Begin("img", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagOnly, "a2014ec7b830377abc4d5e602dde886a75280d5c6202", async() => {
                }
                );
                __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.UrlResolutionTagHelper>();
                __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper);
                __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_0);
                await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
                if (!__tagHelperExecutionContext.Output.IsContentModified)
                {
                    await __tagHelperExecutionContext.SetOutputContentAsync();
                }
                Write(__tagHelperExecutionContext.Output);
                __tagHelperExecutionContext = __tagHelperScopeManager.End();
                WriteLiteral(@"
            <h1>NEWS TODAY</h1>
            <div class=""social-icons"">
                <i class=""fab fa-facebook-f""></i>
                <i class=""fab fa-twitter""></i>
                <i class=""fab fa-google-plus-g""></i>
                <i class=""fab fa-instagram""></i>
                <i class=""fas fa-rss""></i>
            </div>
        </div>
        <nav class=""navbar navbar-expand-md "">
            <!-- Brand -->
            <!-- Toggler/collapsibe Button -->
            <button class=""navbar-toggler"" type=""button"" data-toggle=""collapse"" data-target=""#collapsibleNavbar"">
                <span class=""navbar-toggler-icon""></span>
            </button>

            <!-- Navbar links -->
            <div class=""collapse navbar-collapse"" id=""collapsibleNavbar"">
                <ul class=""navbar-nav"">
                    <li class=""nav-item"">
                        <a class=""nav-link"" href=""Home""></a>
                    </li>
                    <li class=""nav-item"">
                 ");
                WriteLiteral(@"       <a class=""nav-link"" href=""Politics""></a>
                    </li>
                    <li class=""nav-item"">
                        <a class=""nav-link"" href=""International""></a>
                    </li>
                    <li class=""nav-item"">
                        <a class=""nav-link"" href=""Business""></a>
                    </li>
                    <li class=""nav-item"">
                        <a class=""nav-link"" href=""Travel""></a>
                    </li>
                    <li class=""nav-item"">
                        <a class=""nav-link"" href=""Regional""></a>
                    </li>
                    <li class=""nav-item"">
                        <a class=""nav-link"" href=""Sport""></a>
                    </li>
                    <li class=""nav-item"">
                        <a class=""nav-link"" href=""UsersReview""></a>
                    </li>

                    <li class=""nav-item"">
                        <a class=""nav-link"" href=""#""></a>
                    </li>");
                WriteLiteral("\r\n                    <li class=\"nav-item\">\r\n                        ");
                __tagHelperExecutionContext = __tagHelperScopeManager.Begin("a", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "a2014ec7b830377abc4d5e602dde886a75280d5c9564", async() => {
                }
                );
                __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.AnchorTagHelper>();
                __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper);
                __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_1);
                __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper.Page = (string)__tagHelperAttribute_2.Value;
                __tagHelperExecutionContext.AddTagHelperAttribute(__tagHelperAttribute_2);
                __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper.PageHandler = (string)__tagHelperAttribute_3.Value;
                __tagHelperExecutionContext.AddTagHelperAttribute(__tagHelperAttribute_3);
                await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
                if (!__tagHelperExecutionContext.Output.IsContentModified)
                {
                    await __tagHelperExecutionContext.SetOutputContentAsync();
                }
                Write(__tagHelperExecutionContext.Output);
                __tagHelperExecutionContext = __tagHelperScopeManager.End();
                WriteLiteral(@"
                    </li>
                </ul>
            </div>
        </nav>
        <div class=""breaking-news-section"">
            <span id=""btext"">Breaking News</span>
            <marquee direction=""left"" onmouseover=""this.stop()"" onmouseout=""this.start()"">
                <a href=""#"" class=""breaking-news"">
                    <p class=""bntime"">12 Nov 2021</p>
                    Congress under pressure to reach a deal
                </a>
                <a href=""#"" class=""breaking-news""><p class=""bntime"">12 Nov 2021</p>Powerful laser beam is helping track the moon</a>
                <a href=""#"" class=""breaking-news""><p class=""bntime"">12 Nov 2021</p>Snowstorm buries Pacific Northwest, with more on the way</a>
            </marquee>
        </div>
    </header>
    <main>
        <article id=""popular-news"">
            <div id=""featured"">
                <h2>FEATURED</h2>
                <section class=""popular-news-carousel"">
                    <div id=""carousel"" class=""caro");
                WriteLiteral(@"usel slide"" data-ride=""carousel"">
                        <ol class=""carousel-indicators"">
                            <li data-target=""#carouselExampleIndicators"" data-slide-to=""0"" class=""active""></li>
                            <li data-target=""#carouselExampleIndicators"" data-slide-to=""1""></li>
                            <li data-target=""#carouselExampleIndicators"" data-slide-to=""2""></li>
                        </ol>
                        <div class=""carousel-inner"">
                            <div class=""carousel-item active"">
                                <img class=""d-block w-100"" src=""images/carousel1.jpg"" alt=""First slide"">
                                <div class=""carousel-caption d-none d-md-block"">
                                    <h5>Lorem ipsum dolor sit amet, eam tale moderatius</h5>
                                    <p>14th Nov 2021</p></p>
                                </div>
                            </div>
                            <div class=""carousel-item");
                WriteLiteral(@""">
                                <img class=""d-block w-100"" src=""images/carousel2.jpg"" alt=""Second slide"">
                                <div class=""carousel-caption d-none d-md-block"">
                                    <h5>Ut facete iisque scaevola his, his no labores insolens hendrerit. </h5>
                                    <p>14th Nov 2021</p></p>
                                </div>
                            </div>
                            <div class=""carousel-item"">
                                <img class=""d-block w-100"" src=""images/carousel3.jpg"" alt=""Third slide"">
                                <div class=""carousel-caption d-none d-md-block"">
                                    <h5>Habeo populo splendide ei sit, ne vis dicunt saperet voluptatibus.  </h5>
                                    <p>14th Nov 2021</p>
                                </div>
                            </div>
                        </div>
                        <a class=""carousel-control-pre");
                WriteLiteral(@"v"" href=""#carousel"" role=""button"" data-slide=""prev"">
                            <span class=""carousel-control-prev-icon"" aria-hidden=""true""></span>
                            <span class=""sr-only"">Previous</span>
                        </a>
                        <a class=""carousel-control-next"" href=""#carousel"" role=""button"" data-slide=""next"">
                            <span class=""carousel-control-next-icon"" aria-hidden=""true""></span>
                            <span class=""sr-only"">Next</span>
                        </a>
                    </div>
                </section>

            </div>
            <div id=""latest"">
                <h2>LATEST</h2>
                <section class=""news"">
                    <div class=""news-container"">
                        <img src=""images/carousel1.jpg"">
                        <p class=""carousel-text"">This floating entertainment hub</p>
                    </div>
                </section>
                <section class=""news"">
      ");
                WriteLiteral(@"              <div class=""news-container"">
                        <img src=""images/carousel2.jpg"">
                        <p class=""carousel-text"">Repurposed Boeing</p>
                    </div>
                </section>
            </div>
            <div id=""our-picks"">
                <h2>OUR PICKS</h2>
                <section class=""news"">
                    <div class=""news-container"">
                        <img src=""images/carousel3.jpg"">
                        <p class=""carousel-text"">Edinburgh considering tourist tax </p>
                    </div>
                </section>
                <section class=""news"">
                    <div class=""news-container"">
                        <img src=""images/carousel1.jpg"">
                        <p class=""carousel-text"">This floating entertainment hub</p>
                    </div>
                </section>
            </div>
        </article>
        <section class=""more-news"">
            <div class=""news-section"">
    ");
                WriteLiteral(@"            <article class=""world"">
                    <h2>WORLD</h2>
                    <img src=""images/world1.jpg"">
                    <h3>Syria crisis: Obama rejects US military intervention</h3>
                    <p>This is some dummy copy. You’re not really supposed to read this dummy copy, it is just a place holder for people who need some type to visualize what the actual copy might look like if it were real content. If you want to read, I might suggest a good […]</p>
                    <p>AUTHOR: JENNY ADAMS</p>
                    <p>DATE: 13/11/21</p>
                </article>
                <article class=""sport"">
                    <h2>SPORT</h2>
                    <img src=""images/sport1.jpg"">
                    <h3>Lisboa Triathlon 2021</h3>
                    <p>This is some dummy copy. You’re not really supposed to read this dummy copy, it is just a place holder for people who need some type to visualize what the actual copy might look like if it were real content. If ");
                WriteLiteral(@"you want to read, I might suggest a good […]</p>
                    <p>AUTHOR: DANIEL SMITH</p>
                    <p>DATE: 13/09/21</p>
                </article>
            </div>

            <aside>
                <h4>RECENT</h4>
                <div class=""recent-news"">
                    <img src=""images/article1.jpg"">
                    <p>2021 Mercedes-AMG C63 Coupe Makes its Debut</p>
                </div>
                <div class=""recent-news"">
                    <img src=""images/aside2.jpg"">
                    <p>2021 Mercedes-AMG C63 Coupe Makes its Debut</p>
                </div>
                <div class=""recent-news"">
                    <img src=""images/aside3.jpg"">
                    <p>2021 Mercedes-AMG C63 Coupe Makes its Debut</p>
                </div>
                <div class=""recent-news"">
                    <img src=""images/aside4.jpg"">
                    <p>2021 Mercedes-AMG C63 Coupe Makes its Debut</p>
                </div>
                ");
                WriteLiteral(@"<div class=""recent-news"">
                    <img src=""images/aside5.jpg"">
                    <p>2021 Mercedes-AMG C63 Coupe Makes its Debut</p>
                </div>
            </aside>
        </section>
    </main>
    <footer>
        <div class=""social-links"">
            <section class=""about"">
                <h2>About</h2>
                <p>Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Curabitur blandit tempus porttitor. Etiam porta sem malesuada magna mollis euismod.</p>
                <div class=""social-icons-footer"">
                    <i class=""fab fa-facebook""></i>
                    <i class=""fab fa-twitter-square""></i>
                    <i class=""fab fa-google-plus-square""></i>
                    <i class=""fab fa-instagram""></i>
                    <i class=""fas fa-rss-square""></i>
                    <i class=""fab fa-youtube-square""></i>
                    <i class=""fas fa-rss-square""></i>
     ");
                WriteLiteral(@"               <i class=""fab fa-pinterest-square""></i>
                    <i class=""fab fa-linkedin""></i>
                </div>
            </section>
            <section class=""Instagram"">
                <h2>Instagram</h2>
                <img src=""images/aside2.jpg"">
                <img src=""images/aside3.jpg"">
                <img src=""images/aside4.jpg"">
                <img src=""images/aside5.jpg"">
                <img src=""images/aside2.jpg"">
                <img src=""images/aside3.jpg"">
                <img src=""images/aside4.jpg"">
                <img src=""images/aside5.jpg"">
                <img src=""images/aside2.jpg"">
                <button type=""button"" class=""footer-buttons"">View on Instagram</button>
            </section>
            <section class=""Subscribe"">
                <h2>Subscribe to News Today</h2>
                <p>Enter your email address to subscribe to this blog and receive notifications of new posts by email</p>
                <input type=""email"" plac");
                WriteLiteral("eholder=\"Email Address\">\r\n                <button type=\"button\" class=\"footer-buttons\">Subscribe</button>\r\n            </section>\r\n        </div>\r\n\r\n        <div class=\"copyright\">Copyright © 2021 News Today. Designed by Code Spot</div>\r\n    </footer>\r\n\r\n");
            }
            );
            __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_BodyTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.BodyTagHelper>();
            __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_Razor_TagHelpers_BodyTagHelper);
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
            if (!__tagHelperExecutionContext.Output.IsContentModified)
            {
                await __tagHelperExecutionContext.SetOutputContentAsync();
            }
            Write(__tagHelperExecutionContext.Output);
            __tagHelperExecutionContext = __tagHelperScopeManager.End();
            WriteLiteral("\r\n</html>\r\n");
        }
        #pragma warning restore 1998
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.ViewFeatures.IModelExpressionProvider ModelExpressionProvider { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IUrlHelper Url { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IViewComponentHelper Component { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IJsonHelper Json { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper<NewsWebsite.Pages.HomePageModel> Html { get; private set; }
        public global::Microsoft.AspNetCore.Mvc.ViewFeatures.ViewDataDictionary<NewsWebsite.Pages.HomePageModel> ViewData => (global::Microsoft.AspNetCore.Mvc.ViewFeatures.ViewDataDictionary<NewsWebsite.Pages.HomePageModel>)PageContext?.ViewData;
        public NewsWebsite.Pages.HomePageModel Model => ViewData.Model;
    }
}
#pragma warning restore 1591
