#pragma checksum "C:\Users\vera2\source\repos\NewsWebsite\NewsWebsite\Pages\International.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "f283dc07521ff60fbe05aabcf926fbc442b2f447"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(NewsWebsite.Pages.Pages_International), @"mvc.1.0.razor-page", @"/Pages/International.cshtml")]
namespace NewsWebsite.Pages
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.AspNetCore.Mvc.ViewFeatures;
#nullable restore
#line 1 "C:\Users\vera2\source\repos\NewsWebsite\NewsWebsite\Pages\_ViewImports.cshtml"
using NewsWebsite;

#line default
#line hidden
#nullable disable
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"f283dc07521ff60fbe05aabcf926fbc442b2f447", @"/Pages/International.cshtml")]
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"90043ec9aee9334ecbb764efdea4c6fd9611f75b", @"/Pages/_ViewImports.cshtml")]
    public class Pages_International : global::Microsoft.AspNetCore.Mvc.RazorPages.Page
    {
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_0 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("id", new global::Microsoft.AspNetCore.Html.HtmlString("popular-news img"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_1 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("alt", new global::Microsoft.AspNetCore.Html.HtmlString(""), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_2 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("asp-page", "Details", global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        #line hidden
        #pragma warning disable 0649
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext __tagHelperExecutionContext;
        #pragma warning restore 0649
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner __tagHelperRunner = new global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner();
        #pragma warning disable 0169
        private string __tagHelperStringValueBuffer;
        #pragma warning restore 0169
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager __backed__tagHelperScopeManager = null;
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager __tagHelperScopeManager
        {
            get
            {
                if (__backed__tagHelperScopeManager == null)
                {
                    __backed__tagHelperScopeManager = new global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager(StartTagHelperWritingScope, EndTagHelperWritingScope);
                }
                return __backed__tagHelperScopeManager;
            }
        }
        private global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.HeadTagHelper __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_HeadTagHelper;
        private global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.BodyTagHelper __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_BodyTagHelper;
        private global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.UrlResolutionTagHelper __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper;
        private global::Microsoft.AspNetCore.Mvc.TagHelpers.AnchorTagHelper __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper;
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
#nullable restore
#line 5 "C:\Users\vera2\source\repos\NewsWebsite\NewsWebsite\Pages\International.cshtml"
  
    Layout = "Customer_Layout";
    ViewData["Title"] = "International";

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n<html>\r\n");
            __tagHelperExecutionContext = __tagHelperScopeManager.Begin("head", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "f283dc07521ff60fbe05aabcf926fbc442b2f4474575", async() => {
                WriteLiteral(@"

    <link rel=""stylesheet"" href=""https://use.fontawesome.com/releases/v5.7.1/css/all.css"" integrity=""sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr"" crossorigin=""anonymous"">

    <link rel=""stylesheet"" type=""text/css"" href=""css/style.css"">
");
            }
            );
            __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_HeadTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.HeadTagHelper>();
            __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_Razor_TagHelpers_HeadTagHelper);
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
            if (!__tagHelperExecutionContext.Output.IsContentModified)
            {
                await __tagHelperExecutionContext.SetOutputContentAsync();
            }
            Write(__tagHelperExecutionContext.Output);
            __tagHelperExecutionContext = __tagHelperScopeManager.End();
            WriteLiteral("\r\n");
            __tagHelperExecutionContext = __tagHelperScopeManager.Begin("body", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "f283dc07521ff60fbe05aabcf926fbc442b2f4475824", async() => {
                WriteLiteral("\r\n    <main>\r\n");
                WriteLiteral(@"        <section class=""more-news"">
            <div class=""news-section"">
                <article class=""world"">
                    <h2>WORLD</h2>
                    <img src=""images/world1.jpg"">
                    <h3>Syria crisis: Obama rejects US military intervention</h3>
                    <p>This is some dummy copy. You’re not really supposed to read this dummy copy, it is just a place holder for people who need some type to visualize what the actual copy might look like if it were real content. If you want to read, I might suggest a good […]</p>
                    <p>AUTHOR: JENNY ADAMS</p>
                    <p>DATE: 13/11/21</p>
                </article>
                <article class=""sport"">
                    <h2>SPORT</h2>
                    <img src=""images/sport1.jpg"">
                    <h3>Lisboa Triathlon 2021</h3>
                    <p>This is some dummy copy. You’re not really supposed to read this dummy copy, it is just a place holder for people who need some ty");
                WriteLiteral(@"pe to visualize what the actual copy might look like if it were real content. If you want to read, I might suggest a good […]</p>
                    <p>AUTHOR: DANIEL SMITH</p>
                    <p>DATE: 13/09/21</p>
                </article>
            </div>
            <aside>
                <h4>RECENT</h4>
                <div class=""recent-news"">
                    <img src=""images/article1.jpg"">
                    <p>2021 Mercedes-AMG C63 Coupe Makes its Debut</p>
                </div>
                <div class=""recent-news"">
                    <img src=""images/aside2.jpg"">
                    <p>2021 Mercedes-AMG C63 Coupe Makes its Debut</p>
                </div>
                <div class=""recent-news"">
                    <img src=""images/aside3.jpg"">
                    <p>2021 Mercedes-AMG C63 Coupe Makes its Debut</p>
                </div>
                <div class=""recent-news"">
                    <img src=""images/aside4.jpg"">
                    <p>2021 Merce");
                WriteLiteral(@"des-AMG C63 Coupe Makes its Debut</p>
                </div>
                <div class=""recent-news"">
                    <img src=""images/aside5.jpg"">
                    <p>2021 Mercedes-AMG C63 Coupe Makes its Debut</p>
                </div>
            </aside>
            <div class=""news-section"">
                <article class=""world"">
                    <h2>WORLD</h2>
                    <img src=""images/world1.jpg"">
                    <h3>Syria crisis: Obama rejects US military intervention</h3>
                    <p>This is some dummy copy. You’re not really supposed to read this dummy copy, it is just a place holder for people who need some type to visualize what the actual copy might look like if it were real content. If you want to read, I might suggest a good […]</p>
                    <p>AUTHOR: JENNY ADAMS</p>
                    <p>DATE: 13/11/21</p>
                </article>
                <article class=""sport"">
                    <h2>SPORT</h2>
                  ");
                WriteLiteral(@"  <img src=""images/sport1.jpg"">
                    <h3>Lisboa Triathlon 2021</h3>
                    <p>This is some dummy copy. You’re not really supposed to read this dummy copy, it is just a place holder for people who need some type to visualize what the actual copy might look like if it were real content. If you want to read, I might suggest a good […]</p>
                    <p>AUTHOR: DANIEL SMITH</p>
                    <p>DATE: 13/09/21</p>
                </article>

                <article class=""sport"">
                    <h2>SPORT</h2>
                    <img src=""images/sport1.jpg"">
                    <h3>Lisboa Triathlon 2021</h3>
                    <p>This is some dummy copy. You’re not really supposed to read this dummy copy, it is just a place holder for people who need some type to visualize what the actual copy might look like if it were real content. If you want to read, I might suggest a good […]</p>
                    <p>AUTHOR: DANIEL SMITH</p>
                    ");
                WriteLiteral(@"<p>DATE: 13/09/21</p>
                </article>
                <article class=""sport"">
                    <h2>SPORT</h2>
                    <img src=""images/s.jpg"">
                    <h3>Lisboa Triathlon 2021</h3>
                    <p>This is some dummy copy. You’re not really supposed to read this dummy copy, it is just a place holder for people who need some type to visualize what the actual copy might look like if it were real content. If you want to read, I might suggest a good […]</p>
                    <p>AUTHOR: DANIEL SMITH</p>
                    <p>DATE: 13/09/21</p>
                </article>
");
                WriteLiteral("\r\n");
#nullable restore
#line 111 "C:\Users\vera2\source\repos\NewsWebsite\NewsWebsite\Pages\International.cshtml"
                 foreach (News_ClassLibrary.Logic.Classes.NewsArticle cont in Model.News)
                {

                    if (cont.NewsType ==
                    "International-News")

                    {

#line default
#line hidden
#nullable disable
                WriteLiteral("                        <article class=\"sport\">\r\n\r\n                            <h2>");
#nullable restore
#line 120 "C:\Users\vera2\source\repos\NewsWebsite\NewsWebsite\Pages\International.cshtml"
                           Write(cont.NewsType);

#line default
#line hidden
#nullable disable
                WriteLiteral("</h2>\r\n                            <p>");
                __tagHelperExecutionContext = __tagHelperScopeManager.Begin("img", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.SelfClosing, "f283dc07521ff60fbe05aabcf926fbc442b2f44711884", async() => {
                }
                );
                __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.UrlResolutionTagHelper>();
                __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper);
                __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_0);
                BeginAddHtmlAttributeValues(__tagHelperExecutionContext, "src", 2, global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
                AddHtmlAttributeValue("", 6699, "~/photo/", 6699, 8, true);
#nullable restore
#line 121 "C:\Users\vera2\source\repos\NewsWebsite\NewsWebsite\Pages\International.cshtml"
AddHtmlAttributeValue("", 6707, cont.Img, 6707, 9, false);

#line default
#line hidden
#nullable disable
                EndAddHtmlAttributeValues(__tagHelperExecutionContext);
                __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_1);
                await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
                if (!__tagHelperExecutionContext.Output.IsContentModified)
                {
                    await __tagHelperExecutionContext.SetOutputContentAsync();
                }
                Write(__tagHelperExecutionContext.Output);
                __tagHelperExecutionContext = __tagHelperScopeManager.End();
                WriteLiteral("</p>\r\n                            <h3>");
#nullable restore
#line 122 "C:\Users\vera2\source\repos\NewsWebsite\NewsWebsite\Pages\International.cshtml"
                           Write(cont.Title);

#line default
#line hidden
#nullable disable
                WriteLiteral("</h3>\r\n                            <p>");
#nullable restore
#line 123 "C:\Users\vera2\source\repos\NewsWebsite\NewsWebsite\Pages\International.cshtml"
                          Write(cont.Description);

#line default
#line hidden
#nullable disable
                WriteLiteral("</p>\r\n                            <p>");
#nullable restore
#line 124 "C:\Users\vera2\source\repos\NewsWebsite\NewsWebsite\Pages\International.cshtml"
                          Write(cont.NewsType);

#line default
#line hidden
#nullable disable
                WriteLiteral("</p>\r\n                            <p>");
#nullable restore
#line 125 "C:\Users\vera2\source\repos\NewsWebsite\NewsWebsite\Pages\International.cshtml"
                          Write(cont.Author);

#line default
#line hidden
#nullable disable
                WriteLiteral("</p>\r\n                            <p>");
#nullable restore
#line 126 "C:\Users\vera2\source\repos\NewsWebsite\NewsWebsite\Pages\International.cshtml"
                          Write(cont.Date);

#line default
#line hidden
#nullable disable
                WriteLiteral("</p>\r\n");
                WriteLiteral("\r\n                            ");
                __tagHelperExecutionContext = __tagHelperScopeManager.Begin("a", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "f283dc07521ff60fbe05aabcf926fbc442b2f44715086", async() => {
                }
                );
                __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.AnchorTagHelper>();
                __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper);
                __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper.Page = (string)__tagHelperAttribute_2.Value;
                __tagHelperExecutionContext.AddTagHelperAttribute(__tagHelperAttribute_2);
                if (__Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper.RouteValues == null)
                {
                    throw new InvalidOperationException(InvalidTagHelperIndexerAssignment("asp-route-ID", "Microsoft.AspNetCore.Mvc.TagHelpers.AnchorTagHelper", "RouteValues"));
                }
                BeginWriteTagHelperAttribute();
#nullable restore
#line 129 "C:\Users\vera2\source\repos\NewsWebsite\NewsWebsite\Pages\International.cshtml"
                                                    WriteLiteral(cont.NewsID);

#line default
#line hidden
#nullable disable
                __tagHelperStringValueBuffer = EndWriteTagHelperAttribute();
                __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper.RouteValues["ID"] = __tagHelperStringValueBuffer;
                __tagHelperExecutionContext.AddTagHelperAttribute("asp-route-ID", __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper.RouteValues["ID"], global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
                await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
                if (!__tagHelperExecutionContext.Output.IsContentModified)
                {
                    await __tagHelperExecutionContext.SetOutputContentAsync();
                }
                Write(__tagHelperExecutionContext.Output);
                __tagHelperExecutionContext = __tagHelperScopeManager.End();
                WriteLiteral("\r\n                        </article>\r\n");
#nullable restore
#line 131 "C:\Users\vera2\source\repos\NewsWebsite\NewsWebsite\Pages\International.cshtml"

                    }
                }

#line default
#line hidden
#nullable disable
                WriteLiteral("\r\n            </div>\r\n        </section>\r\n    </main>\r\n\r\n");
            }
            );
            __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_BodyTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.BodyTagHelper>();
            __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_Razor_TagHelpers_BodyTagHelper);
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
            if (!__tagHelperExecutionContext.Output.IsContentModified)
            {
                await __tagHelperExecutionContext.SetOutputContentAsync();
            }
            Write(__tagHelperExecutionContext.Output);
            __tagHelperExecutionContext = __tagHelperScopeManager.End();
            WriteLiteral("\r\n</html>\r\n\r\n");
        }
        #pragma warning restore 1998
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.ViewFeatures.IModelExpressionProvider ModelExpressionProvider { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IUrlHelper Url { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IViewComponentHelper Component { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IJsonHelper Json { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper<NewsWebsite.Pages.InternationalModel> Html { get; private set; }
        public global::Microsoft.AspNetCore.Mvc.ViewFeatures.ViewDataDictionary<NewsWebsite.Pages.InternationalModel> ViewData => (global::Microsoft.AspNetCore.Mvc.ViewFeatures.ViewDataDictionary<NewsWebsite.Pages.InternationalModel>)PageContext?.ViewData;
        public NewsWebsite.Pages.InternationalModel Model => ViewData.Model;
    }
}
#pragma warning restore 1591
